version: '2'

services:
  master:
    container_name: 'citus_master'
    image: 'lukashes/citus-docker:5.2.2'
    ports: ['5532:5432']
    labels: ['com.citusdata.role=Master']
  worker:
    image: 'lukashes/citus-docker:5.2.2'
    labels: ['com.citusdata.role=Worker']
  config:
    container_name: 'citus_config'
    image: 'citusdata/workerlist-gen:0.9.0'
    volumes: ['/var/run/docker.sock:/tmp/docker.sock']
    volumes_from: ['master']
