name: Build and publish Docker images on demand

on:
  workflow_dispatch:
    inputs:
      trigger_type:
        description: "Type of build which you want to trigger. Allowed values: main, tags, nightly"
      tag_name:
        description: "The tag name on the project repo to be released. It is mandatory if you select the trigger_type as 'tags' "

jobs:

  build_and_publish_images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_type: [ latest, alpine, postgres_12, nightly ]
    steps:
      - name: Checkout docker repository
        uses: actions/checkout@v2

      - name: Clone tools repository
        run: git clone --depth=1 --branch tools-transition-update-docker https://github.com/citusdata/tools.git tools

      - name: Install package dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev

      - name: Install python dependencies
        run: python -m pip install -r tools/packaging_automation/requirements.txt

